# Site
name: "Electrical Engineering IITB Batch of 2021"
title: "Batch Website"
description: "An amalgamation of four-years of memory made together at the most-BT Department of all! "
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: vedantsatav.github.io
baseurl: '/Elec2021'
google_analytics: 'UA-164894332-1 '
# disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: vedantanilsatav@gmail.com

# Authors
authors:
  sal:
    name: Vedant Satav
    display_name: Vedant
    avatar: 'assets/images/avatar-sal.png'
    email: vedantanilsatav@gmail.com
    web: https://vedantsatav.github.io/about
    twitter: https://twitter.com/VedantSatav1
    description: "Forever CR, part-time DGSec. Drama, Doggo and Drive to Survive."
  john:
    name: Syomantak Chaudhuri
    display_name: Syomantak    
    avatar: 'assets/images/avatar.png'
    email: syomantak.c@gmail.com
    web: https://www.sites.google.com/view/syomantak
    description: "The guy with the most, and the least, power simulataneoulsy. Closeted creep."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
